Repository zhinst/zhinst-toolkit, pull requests merged in 2022-03, with the labels that each got.

#102 Improve missing AWG-option handling when calling the awg module
  src/zhinst/toolkit/driver/devices/uhfli.py
  src/zhinst/toolkit/driver/devices/uhfqa.py
  tests/test_uhfli.py
  tests/test_uhfqa.py
Labels: bug

#100 Reintroduce the uhfqa.qa_delay function as uhfqa.qas.adjusted_delay
  src/zhinst/toolkit/driver/devices/uhfqa.py
  tests/test_uhfqa.py
Labels: enhancement

#107 Create temporary awg_module for each sequencer upload
  src/zhinst/toolkit/driver/devices/hdawg.py
  src/zhinst/toolkit/driver/devices/shfqa.py
  src/zhinst/toolkit/driver/devices/shfsg.py
  src/zhinst/toolkit/driver/devices/uhfli.py
  src/zhinst/toolkit/driver/nodes/awg.py
  src/zhinst/toolkit/driver/nodes/generator.py
  tests/test_generator.py
Labels: bug

#109 Fix missing typehint sequencer program
  src/zhinst/toolkit/driver/nodes/generator.py
Labels: documentation

#111 Adapt hf2 nodetree to correctly support pids
  src/zhinst/toolkit/resources/nodedoc_hf2.json
Labels: bug

#113 Adapt nodetree to be able to get daq result data
  src/zhinst/toolkit/nodetree/node.py
Labels: bug

#114 Add write_integration_weight function to UHFQA integration
  CHANGELOG.md
  src/zhinst/toolkit/driver/devices/uhfqa.py
  tests/test_uhfqa.py
Labels: enhancement
