Repository zhinst/zhinst-toolkit, pull requests merged in 2022-04, with the labels that each got.

#115 Add fallback for wildcard get on HF2
  src/zhinst/toolkit/nodetree/node.py
  tests/test_nodetree.py
Labels: bug

#116 Contributing section to documentation
  CONTRIBUTING.rst
  docs/source/contributing/index.rst
  docs/source/index.rst
Labels: documentation

#117 Improve docs documentation and requirements
  CONTRIBUTING.rst
  docs/requirements.txt
Labels: bug, documentation

#120 docs: Add exceptions module and ValidationError docstring
  src/zhinst/toolkit/exceptions.py
Labels: documentation

#122 Add docs, release notes and source project URLs
  setup.cfg
Labels: documentation

#123 Update requirements.txt
  requirements.txt
Labels: enhancement

#124 Github CI tests run on multiple Python versions
  .github/workflows/ci.yml
Labels: enhancement

#129 Fix while loop in sequence
  examples/hdawg_awg.md
Labels: bug

#126 Black and isort format on src and tests, add SHFQC to isort skip
  src/zhinst/toolkit/__init__.py
  src/zhinst/toolkit/driver/devices/__init__.py
  src/zhinst/toolkit/driver/devices/base.py
  src/zhinst/toolkit/driver/devices/hdawg.py
  src/zhinst/toolkit/driver/devices/shfqa.py
  src/zhinst/toolkit/driver/devices/shfqc.py
  src/zhinst/toolkit/driver/devices/uhfli.py
  src/zhinst/toolkit/driver/devices/uhfqa.py
  src/zhinst/toolkit/driver/modules/base_module.py
  src/zhinst/toolkit/driver/modules/daq_module.py
  src/zhinst/toolkit/driver/nodes/awg.py
  src/zhinst/toolkit/driver/nodes/shfqa_scope.py
  src/zhinst/toolkit/driver/nodes/spectroscopy.py
  src/zhinst/toolkit/driver/parsers.py
  src/zhinst/toolkit/exceptions.py
  src/zhinst/toolkit/session.py
  tests/conftest.py
  tests/test_awg.py
  tests/test_base.py
  tests/test_generator.py
  tests/test_nodetree.py
  tests/test_pqsc.py
  tests/test_shfqa.py
  tests/test_shfsg.py
  tests/test_spectroscopy.py
  tests/test_uhfli.py
  tests/test_uhfqa.py
Labels: enhancement

#128 Add tox
  .github/workflows/ci.yml
  tox.ini
Labels: enhancement

#130 Add SHFQC to DeviceType
  src/zhinst/toolkit/driver/devices/__init__.py
Labels: bug

#131 Add publish to PyPi workflow
  .github/workflows/publish.yml
  build_tools/test_wheels.sh
Labels: enhancement

#132 Add flake8 to GitHub CI, make it pass
  .github/workflows/lint.yml
  pyproject.toml
  scripts/zhinst_toolkit_symlink.py
  setup.cfg
  src/zhinst/toolkit/driver/devices/uhfqa.py
  src/zhinst/toolkit/driver/nodes/awg.py
  src/zhinst/toolkit/driver/nodes/command_table_node.py
  src/zhinst/toolkit/nodetree/node.py
  tox.ini
Labels: enhancement

#133 Add black to CI
  .github/workflows/lint.yml
  pyproject.toml
  scripts/tests/test_zhinst_toolkit_symlink.py
  scripts/zhinst_toolkit_symlink.py
  src/zhinst/toolkit/nodetree/connection_dict.py
  tox.ini
Labels: enhancement

#125 Add mypy
  .github/workflows/lint.yml
  setup.cfg
Labels: enhancement
