Repository zhinst/zhinst-toolkit, pull requests merged in 2022-07, with the labels that each got.

#157 Improve write_to_waveform_memory
  CHANGELOG.md
  src/zhinst/toolkit/driver/nodes/awg.py
  tests/test_awg.py
Labels: enhancement

#160 Spelling output stdout, no artifacts
  .github/workflows/docs.yml
Labels: documentation, enhancement

#161 Introduce WildcardResult class
  CHANGELOG.md
  docs/requirements.txt
  docs/source/examples/common_device.rst
  examples/nodetree.md
  src/zhinst/toolkit/nodetree/node.py
  tests/test_nodetree.py
Labels: bug, enhancement
